version: '3.1'
volumes:
        dbdata:
services:
  db:
    image: postgres
    environment:
            - POSTGRES_USER=example
            - POSTGRES_PASSWORD=myexample
            - POSTGRES_DB=dbexample
    ports:
    - "5432:5432"
    volumes:
            - dbdata:/var/lib/postgresql/data
